import {
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SET_INITIAL_DATA,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_LOCATION,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_CURRENCY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_INDUSTRY_OPERATING,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_INDUSTRY_OPERATING,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_AVERAGE_VALUE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_AVERAGE_VALUE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_AVERAGE_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_AVERAGE_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SOURCE_FUNDS_START,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SOURCE_FUNDS_START,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_INITIAL_FUNDS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_INITIAL_FUNDS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_COMPANY_ACTIVITIES,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_COMPANY_ACTIVITIES,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SUBSIDIARY_COMPANY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_MAIN_SUPLIERS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_MAIN_SUPLIERS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_NAME_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_NAME_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_LINK_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_LINK_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_VALUE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_VALUE_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_NUMBER_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_COMPANY_SERVICES,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES_NAME_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES_NAME_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_ADD_MAIN_SUPPLIER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_DELETE_MAIN_SUPPLIER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_LINK_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_LINK_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_NAME_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_NAME_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_BB,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_BC,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_MALTA_SALES_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_MALTA_SALES_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_WITHIN_SALES_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_WITHIN_SALES_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_OUTSIDE_SALES_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_OUTSIDE_SALES_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_VALUE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_VALUE_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_NUMBER_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_MALTA_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_MALTA_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_WITHIN_EU,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_WITHIN_EU_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_OUTSIDE_EU,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_OUTSIDE_EU_BLUR,
} from "../../constants/actionTypes";

import {createAction} from "redux-actions";

export const set_initial_data = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SET_INITIAL_DATA,(countries, currencies,share_types) =>({countries, currencies,share_types}))
export const chnageLocation = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_LOCATION,(value) =>({value}))
export const changeCurrency = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_CURRENCY,(value) =>({value}))
export const changeIndustryOperating = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_INDUSTRY_OPERATING,(value) =>({value}))
export const blurOperatingIndustry = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_INDUSTRY_OPERATING,(value) =>({value}))
export const changeAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_AVERAGE_VALUE,(value) =>({value}))
export const blurAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_AVERAGE_VALUE,(value) =>({value}))
export const changeAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_AVERAGE_NUMBER,(value) =>({value}))
export const blurAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_AVERAGE_NUMBER,(value) =>({value}))
export const changeSourceFundsStart = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SOURCE_FUNDS_START,(value) =>({value}))
export const blurSourceFundsStart = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SOURCE_FUNDS_START,(value) =>({value}))
export const changeInitialFunds = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_INITIAL_FUNDS,(value) =>({value}))
export const blurInitialFunds = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_INITIAL_FUNDS,(value) =>({value}))
export const changeCompanyActivities = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_COMPANY_ACTIVITIES,(value) =>({value}))
export const blurCompanyActivities = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_COMPANY_ACTIVITIES,(value) =>({value}))
export const addSubsidiaryCompany = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SUBSIDIARY_COMPANY,(value) =>({value}))
export const onClickAddMainSuppliers = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_MAIN_SUPLIERS,(value) =>({value}))
export const onClickDeleteMainSupplier = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_MAIN_SUPLIERS,(value) =>({value}))
export const onChangeMainSupplierName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_NAME_CHANGE,(index,value) =>({index, value}))
export const blurMainSupplierName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_NAME_BLUR,(index,value) =>({index, value}))
export const onChangeMainSupplierLink = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_LINK_CHANGE,(index,value) =>({index, value}))
export const blurMainSupplierLink = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_LINK_BLUR,(index,value) =>({index, value}))
export const changeMainSupplierAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_VALUE,(value) =>({value}))
export const onBlurMainSupplierAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_VALUE_BLUR,(value) =>({value}))
export const changeMainSupplierAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_NUMBER,(value) =>({value}))
export const onBlurMainSupplierAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_MAIN_SUPLIERS_AVERAGE_NUMBER_BLUR,(value) =>({value}))
export const onClickAddCompanyOfferedService = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_COMPANY_SERVICES,(value) =>({value}))
export const onClickDeleteCompanyService = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES,(value) =>({value}))
export const changeCompanyServiceName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES_NAME_CHANGE,(index,value) =>({index,value}))
export const blurCompanyServiceName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_COMPANY_SERVICES_NAME_BLUR,(index,value) =>({index,value}))
export const onClickAddSalesMainSupplier = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_ADD_MAIN_SUPPLIER,(value) =>({value}))
export const onClickDeleteSalesAreMainSupplier = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_DELETE_MAIN_SUPPLIER,(value) =>({value}))
export const blurSalesAreMainSupplierLink = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_LINK_BLUR,(index, value) =>({index, value}))
export const onChangeSalesAreMainSupplierLink = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_LINK_CHANGE,(index, value) =>({index, value}))
export const onChangeSalesAreMainSupplierName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_NAME_CHANGE,(index, value) =>({index, value}))
export const blurSalesAreMainSupplierName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_MAIN_SUPPLIER_NAME_BLUR,(index, value) =>({index, value}))
export const onClickBB = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_BB,(index, value) =>({index, value}))
export const onClickBC = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SALES_ARE_BC,(index, value) =>({index, value}))
export const changeSalesInMalta = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_MALTA_SALES_CHANGE,(value) =>({value}))
export const blurSalesInMalta = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_MALTA_SALES_BLUR,(value) =>({value}))
export const changeSalesWithinEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_WITHIN_SALES_CHANGE,(value) =>({value}))
export const blurSalesWithin = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_WITHIN_SALES_BLUR,(value) =>({value}))
export const changeSalesOutsideEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_OUTSIDE_SALES_CHANGE,(value) =>({value}))
export const blurSalesOutsideEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_OUTSIDE_SALES_BLUR,(value) =>({value}))
export const changeSalesAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_VALUE,(value) =>({value}))
export const blurSalesAverageValue = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_VALUE_BLUR,(value) =>({value}))
export const changeSalesAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_NUMBER,(value) =>({value}))
export const blurSalesAverageNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_SALES_AVERAGE_NUMBER_BLUR,(value) =>({value}))
export const changeForecastedPurchasesInMalta = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_MALTA_CHANGE,(value) =>({value}))
export const blurForecastedPurchasesInMalta = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_MALTA_BLUR,(value) =>({value}))
export const changeForecastedPurchasesWithinEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_WITHIN_EU,(value) =>({value}))
export const blurForecastedPurchasesWithinEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_WITHIN_EU_BLUR,(value) =>({value}))
export const changeForecastedPurchasesOutsideEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_OUTSIDE_EU,(value) =>({value}))
export const blurForecastedPurchasesOutsideEU = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_FORECASTED_PURCHCASES_OUTSIDE_EU_BLUR,(value) =>({value}))
