import {
  CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SUBSIDIARY_COMPANY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_NAME,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_NAME,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_REGISTRATION_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_REGISTRATION_NUMBER,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_DOMICILE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_DOMICILE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_ADDRESS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_ADDRESS,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_ACTIVITY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_ACTIVITY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SHARE_CAPITAL_TO_SUBSIDIARY_COMPANY,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_NUMBER_OF_SHARES_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_NUMBER_OF_SHARES_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_TYPE_OF_SHARE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_CLASS_OF_SHARES,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_CLASS_OF_SHARE_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_VALUE_PER_SHARE_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_VALUE_PER_SHARE_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_PAID_UP_CHANGE,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_PAID_UP_BLUR,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_SHARE_CAPITAL,
  CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_SUBSIDIARY_COMPANY,
} from "../../constants/actionTypes";

import {createAction} from "redux-actions";

export const addSubsidiaryCompany = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SUBSIDIARY_COMPANY,(value) =>({value}))
export const changeSubsidiaryCompanyName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_NAME,(index,value) =>({index, value}))
export const blurSubsidiaryCompanyName = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_NAME,(index,value) =>({index, value}))
export const changeRegistrationNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_REGISTRATION_NUMBER,(index,value) =>({index, value}))
export const blurSubsidiaryCompanyRegistrationNumber = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_REGISTRATION_NUMBER,(index,value) =>({index, value}))
export const changeDomicile = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_DOMICILE,(index,value) =>({index, value}))
export const blurSubsidiaryCompanyDomicile = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_DOMICILE,(index,value) =>({index, value}))
export const changeAddress = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_ADDRESS,(index,value) =>({index, value}))
export const blurSubsidiaryCompanyAddress = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_ADDRESS,(index,value) =>({index, value}))
export const changeActivity = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_CHANGE_SUBSIDIARY_COMPANY_ACTIVITY,(index,value) =>({index, value}))
export const blurSubsidiaryCompanyActivity = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_BLUR_SUBSIDIARY_COMPANY_ACTIVITY,(index,value) =>({index, value}))
export const addShareCapitalToSubsidiaryCompany = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_ADD_SHARE_CAPITAL_TO_SUBSIDIARY_COMPANY,(index) =>({index}))
export const subsidiaryCompanyShareNumberChamge = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_NUMBER_OF_SHARES_CHANGE,(x, y, value) =>({x, y, value}))
export const blurSubsidiaryCompanyShareCapitalNumberOfShares = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_NUMBER_OF_SHARES_BLUR,(x, y, value) =>({x, y, value}))
export const changeShareCapital = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_TYPE_OF_SHARE,(x, y, value) =>({x, y, value}))
export const onChangeShareCapitalClassNameOfShares = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_CLASS_OF_SHARES,(x, y, value) =>({x, y, value}))
export const blurSubsidiaryCompanyShareCapitalClassOfShare = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_CLASS_OF_SHARE_BLUR,(x, y, value) =>({x, y, value}))
export const onChangeShareCapitalChangeValuePerShare = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_VALUE_PER_SHARE_CHANGE,(x, y, value) =>({x, y, value}))
export const blurSubsidiaryCompanyShareCapitalValuePerShare = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_VALUE_PER_SHARE_BLUR,(x, y, value) =>({x, y, value}))
export const onChangeShareCapitalChangePaidUp = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_PAID_UP_CHANGE,(x, y, value) =>({x, y, value}))
export const blurSubsidiaryCompanyShareCapitalPaidUp = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_SHARE_CAPITAL_PAID_UP_BLUR,(x, y, value) =>({x, y, value}))
export const deleteShareCapital = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_SHARE_CAPITAL,(x, y) =>({x, y}))
export const onClickDeleteSubsidiaryCompany = createAction(CREATE_COMPANY_ACTIVITIES_INFORMATION_DELETE_SUBSIDIARY_COMPANY,(x) =>({x}))

